services:
  - type: web
    name: olenadimabud
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn OlenaDimaBud.wsgi"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: OlenaDimaBud.settings
